### ISSUE TITLE
Mounted files lack exec bit on Windows

### ISSUE THREAD

**Issue by tatroc** [canonical/multipass#1252]
when I mount windows directory from multipass, how do I set the exec flag so I can execute scripts on the mount?

 Is there a way to specify a mount option?

For example, if I run this I am unable to execute scripts on windows mount
multipass mount c:\temp primary

**Comment by Saviq** [comment]
Hi @tatroc you're right, since the file permissions don't match between Windows and *nixes, we don't have a way to know if a file should have been executable…

The couple workarounds I can offer straight up is running the scripts explicitly with their interpreter:
```console
$ python path/to/script
```
or share whatever you need via Windows file sharing and [mount it using cifs](https://wiki.ubuntu.com/MountWindowsSharesPermanently).

We'll have a think on how to improve this (not sure if adding exec to all the files by default is a good option, maybe we need to expose such options on the `multipass mount` command).

**Comment by dbrennan** [comment]
Is there any possibility of using extended attributes of NTFS if that is the underlying Windows filesystem? Sorry I'm not up to speed on how the mount passthru works and if this is even feasible, but it's one idea.

**Comment by legezam** [comment]
> 
> 
> Hi @tatroc you're right, since the file permissions don't match between Windows and *nixes, we don't have a way to know if a file should have been executable…
> 
> The couple workarounds I can offer straight up is running the scripts explicitly with their interpreter:
> 
> ```
> $ python path/to/script
> ```
> 
> or share whatever you need via Windows file sharing and [mount it using cifs](https://wiki.ubuntu.com/MountWindowsSharesPermanently).
> 
> We'll have a think on how to improve this (not sure if adding exec to all the files by default is a good option, maybe we need to expose such options on the `multipass mount` command).

Unfortunately the first workaround doesn't work for .net core cli for some reason, i get this error:
```
System.ComponentModel.Win32Exception (13): Permission denied
   at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Microsoft.DotNet.Cli.Utils.Command.Execute()
   at Microsoft.DotNet.Tools.Run.RunCommand.Execute()
   at Microsoft.DotNet.Tools.Run.RunCommand.Run(String[] args)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
```

**Comment by c-goes** [comment]
Here is a workaround for compiled Go programs:

First run ldd to find the correct interpreter

```
ldd test
        linux-vdso.so.1 (0x00007fffcdddb000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f6ddf588000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f6ddf197000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f6ddf7a7000)
```

In this case `/lib64/ld-linux-x86-64.so.2`

now run `/lib64/ld-linux-x86-64.so.2 ./test`

**Comment by brujah** [comment]
No update on this?

**Comment by arafatx** [comment]
This is the only issue that want me to go back to real virtual box terminal where the bash script does not even care about execution bit

**Comment by arafatx** [comment]
>  maybe we need to expose such options on the `multipass mount` command).

+1 . The mount option should have many options like the linux mount option

**Comment by arafatx** [comment]
This is the only issue that want me to go back to real virtual box terminal where the bash script does not even care about execution bit and the problem with the workaround having the 'bash' in front you also need to include this in every command in statement inside bash script.

maybe we need to expose such options on the multipass mount command).

+1 . The mount option should have many options like the linux mount option. I wish to see --read-only for just reading mount path.

**Comment by jianzhong** [comment]
Has anyone found a solution? The ticket has been opened for over 3 years. 
Also, my confidence on using this software become very low. Because of the missing exec bit issue, I had to copy shared folders to another location inside the VM. But next day, the VM may failed to start, and I had lost all my work inside the VM. This happened several times!

**Comment by tatroc** [comment]
I switched to wsl2, if on Mac others are using Lima-vm

**Comment by townsend2010** [comment]
Hey all,

Sorry for the lack of activity on this issue.  We are planning on addressing many of the issues seen with our mounting solutions and we will look into if there is a way to fix this issue as well.

**Comment by townsend2010** [comment]
Hey all who are affected by this!

I've done some research on this.  we use Qt to abstract away many of the platform dependent parts and so I poked around Qt code to figure out what exactly it is doing on Windows when it comes to permissions on NTFS.  So I found that if you name a file with either the `.exe`, `.com`, `.bat`, `.pif`, or `,cmd`, it will execute the file as if the execute bit is set.  This is all a limitation of Qt unless we explicitly tell it to use NTFS file permissions which supposedly has a pretty severe performance penalty.  That said, we can try enabling that and see what the effect is.

**Comment by limfjm** [comment]
I encountered this issue, especially with my bash script. 

I went back to WSL/VM to execute my script. I hope that it will be available in multipass.

**Comment by townsend2010** [comment]
Hi @limfjm,

As I [previously pointed out](https://github.com/canonical/multipass/issues/1252#issuecomment-1799989702), this is a limitation of how Qt works with respect to Windows file permissions.  If you add one of those suffixes to the name of your bash script, it *might* work.

**Comment by DenisBalan** [comment]
need this to work on windows mounts
for now we can just copy files to directory inside vm
but thats not the correct way to go

**Comment by tobe2098** [comment]
Hi all, we are researching a move away from Qt. Hopefully this will address the issue.
