### ISSUE TITLE
[qemu] crash when starting instance in UNKNOWN state

### ISSUE THREAD

**Issue by Saviq** [canonical/multipass#1360]
Steps to repro:
- `multipass launch -n crash`
- `snap stop multipass`
- `sudo vim /var/snap/multipass/common/data/multipassd/multipassd-vm-instances.json`
- clear the `machine_type` field
- `snap start multipass`
- `multipass start crash`
- wait for it to die
- `multipass start crash`
- SIGSEGV:
```gdb
#0  0x000055615ce6581b in multipass::QemuVirtualMachine::start (this=0x556165c00150) at /build/multipass/parts/multipass/src/src/platform/backends/qemu/qemu_virtual_machine.cpp:256
No locals.
#1  0x000055615ce14222 in multipass::Daemon::start (this=0x7ffc21d800c0, request=0x7f5ad401ff10, server=0x7f5aeae7d830, status_promise=0x7f5aeae7d720) at /build/multipass/parts/multipass/src/src/daemon/daemon.cpp:1440
        it = {<std::__detail::_Node_iterator_base<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::shared_ptr<multipass::VirtualMachine> >, true>> = {_M_cur = 0x556165c04400}, <No data fields>}
        state = <optimized out>
        name = <optimized out>
        __for_range = @0x7ffc21d7f900: {<std::_Vector_base<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >> = {
            _M_impl = {<std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >> = {<__gnu_cxx::new_allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >> = {<No data fields>}, <No data fields>}, _M_start = 0x5561663deae0, _M_finish = 0x5561663deb00, _M_end_of_storage = 0x5561663deb00}}, <No data fields>}
        __for_begin = <optimized out>
        __for_end = <optimized out>
        logger = {<multipass::logging::Logger> = {_vptr.Logger = 0x55615d637d48 <vtable for multipass::logging::ClientLogger<multipass::StartReply>+16>}, logging_level = multipass::logging::Level::error, server = 0x7f5aeae7d830, mpx_logger = @0x556165bcdad0}
        start_error = {<google::protobuf::Message> = {<google::protobuf::MessageLite> = {_vptr.MessageLite = 0x55615d643d28 <vtable for multipass::StartError+16>}, <No data fields>}, static kIndexInFileMessages = 40, 
          static OK = multipass::StartError_ErrorCode_OK, static DOES_NOT_EXIST = multipass::StartError_ErrorCode_DOES_NOT_EXIST, static INSTANCE_DELETED = multipass::StartError_ErrorCode_INSTANCE_DELETED, static OTHER = multipass::StartError_ErrorCode_OTHER, 
          static ErrorCode_MIN = multipass::StartError_ErrorCode_OK, static ErrorCode_MAX = multipass::StartError_ErrorCode_OTHER, static ErrorCode_ARRAYSIZE = 4, static kInstanceErrorsFieldNumber = 1, 
          _internal_metadata_ = {<google::protobuf::internal::InternalMetadataWithArenaBase<google::protobuf::UnknownFieldSet, google::protobuf::internal::InternalMetadataWithArena>> = {ptr_ = 0x0, static kPtrTagMask = 1, 
              static kPtrValueMask = -2}, <No data fields>}, 
          instance_errors_ = {<google::protobuf::internal::TypeDefinedMapFieldBase<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, multipass::StartError_ErrorCode>> = {<google::protobuf::internal::MapFieldBase> = {
                _vptr.MapFieldBase = 0x55615d641908 <vtable for google::protobuf::internal::MapField<multipass::StartError_InstanceErrorsEntry_DoNotUse, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, multipass::StartError_ErrorCode, (google::protobuf::internal::WireFormatLite::FieldType)9, (google::protobuf::internal::WireFormatLite::FieldType)14, 0>+16>, arena_ = 0x0, repeated_field_ = 0x0, mutex_ = {mu_ = {<std::__mutex_base> = {_M_mutex = {__data = {__lock = 0, __count = 0, 
                          __owner = 0, __nusers = 0, __kind = 0, __spins = 0, __elision = 0, __list = {__prev = 0x0, __next = 0x0}}, __size = '\000' <repeats 39 times>, __align = 0}}, <No data fields>}}, state_ = {static _S_min_alignment = 4, 
                  static _S_alignment = 4, _M_i = google::protobuf::internal::MapFieldBase::STATE_MODIFIED_MAP}}, <No data fields>}, static kIsValueEnum = true, impl_ = {arena_ = 0x0, map_ = {arena_ = 0x0, default_enum_value_ = 0, 
                elements_ = 0x556165bff710}}}, _cached_size_ = {size_ = {<std::__atomic_base<int>> = {static _S_alignment = 4, _M_i = 0}, static is_always_lock_free = true}}}
        future_watcher = <optimized out>
        errors = 0x7ffc21d7fa70
        vms = {<std::_Vector_base<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >> = {
            _M_impl = {<std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >> = {<__gnu_cxx::new_allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >> = {<No data fields>}, <No data fields>}, _M_start = 0x5561663deae0, _M_finish = 0x5561663deb00, _M_end_of_storage = 0x5561663deb00}}, <No data fields>}
```

Part of the problem is it seems we're not noticing QEMU died (because of the missing machine_type value).

**Comment by tobe2098** [comment]
I have repeated the recipe with different Ubuntu versions and the error does not reproduce. Changing the recipe so that the daemon uses the machine_type:
- First susupend the machine
- Close the daemon
- Edit the json
- Start the daemon
- Start the machine
In this case, the default machine is not found and the argument is not passed on start. This means qemu uses the default machine type for the computer. This works perfectly fine using the non-snap version of multipass, and the snap version of multipass, so I am closing this issue.

The machine type can be regenerated by stopping and starting the VM.
