### ISSUE TITLE
[qemu] race-y crash on timed out suspend

### ISSUE THREAD

**Issue by Saviq** [canonical/multipass#1581]
```gdb
#0  multipass::QemuVirtualMachine::<lambda()>::operator() (__closure=0x56459dba8cb0) at /root/parts/multipass/src/src/platform/backends/qemu/qemu_virtual_machine.cpp:484
        qmp_output = {
          d = 0x56459bc7ca7e <fmt::v6::internal::parse_format_string<false, char, fmt::v6::format_handler<fmt::v6::arg_formatter<fmt::v6::buffer_range<char> >, char, fmt::v6::basic_format_context<std::back_insert_iterator<fmt::v6::internal::buffer<char> >, char> >&>(fmt::v6::basic_string_view<char>, fmt::v6::format_handler<fmt::v6::arg_formatter<fmt::v6::buffer_range<char> >, char, fmt::v6::basic_format_context<std::back_insert_iterator<fmt::v6::internal::buffer<char> >, char> >&)+2222>}
        qmp_object = {d = 0x56459db49030, o = 0x52}
        event = {{a = 0x7f75da7ce812, o = 0x7f75da7ce812}, is_object = 1, index = 0}
        this = 0x56459db0eb00
        this = <optimized out>
        qmp_output = <optimized out>
        qmp_object = <optimized out>
        event = <optimized out>
#1  QtPrivate::FunctorCall<QtPrivate::IndexesList<>, QtPrivate::List<>, void, multipass::QemuVirtualMachine::initialize_vm_process()::<lambda()> >::call (arg=0x7fff9a1a6020, f=...) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h:130
No locals.
#2  QtPrivate::Functor<multipass::QemuVirtualMachine::initialize_vm_process()::<lambda()>, 0>::call<QtPrivate::List<>, void> (arg=0x7fff9a1a6020, f=...) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h:240
No locals.
#3  QtPrivate::QFunctorSlotObject<multipass::QemuVirtualMachine::initialize_vm_process()::<lambda()>, 0, QtPrivate::List<>, void>::impl(int, QtPrivate::QSlotObjectBase *, QObject *, void **, bool *) (which=<optimized out>, this_=0x56459dba8ca0, 
    r=0x56459eb91240, a=0x7fff9a1a6020, ret=0x0) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qobject_impl.h:168
No locals.
#4  0x00007f75d957266f in QMetaObject::activate(QObject*, int, int, void**) () from target:/snap/multipass/2161/usr/lib/x86_64-linux-gnu/libQt5Core.so.5
No symbol table info available.
#5  0x00007f75d957266f in QMetaObject::activate(QObject*, int, int, void**) () from target:/snap/multipass/2161/usr/lib/x86_64-linux-gnu/libQt5Core.so.5
No symbol table info available.
#6  0x00007f75d94be38a in QProcess::readyReadStandardOutput(QProcess::QPrivateSignal) () from target:/snap/multipass/2161/usr/lib/x86_64-linux-gnu/libQt5Core.so.5
No symbol table info available.
#7  0x00007f75d94c4d79 in ?? () from target:/snap/multipass/2161/usr/lib/x86_64-linux-gnu/libQt5Core.so.5
No symbol table info available.
#8  0x00007f75d94c9f98 in ?? () from target:/snap/multipass/2161/usr/lib/x86_64-linux-gnu/libQt5Core.so.5
No symbol table info available.
#9  0x00007f75d94bfabb in QProcess::waitForFinished(int) () from target:/snap/multipass/2161/usr/lib/x86_64-linux-gnu/libQt5Core.so.5
No symbol table info available.
#10 0x00007f75d94c023a in QProcess::~QProcess() () from target:/snap/multipass/2161/usr/lib/x86_64-linux-gnu/libQt5Core.so.5
No symbol table info available.
#11 0x000056459bd0b0cd in multipass::BasicProcess::CustomQProcess::~CustomQProcess (this=<optimized out>, __in_chrg=<optimized out>) at /root/parts/multipass/src/src/platform/backends/shared/basic_process.h:68
No locals.
#12 multipass::BasicProcess::~BasicProcess (this=0x56459eb91240, __in_chrg=<optimized out>) at /root/parts/multipass/src/src/platform/backends/shared/basic_process.h:32
No locals.
#13 0x000056459bcfd048 in (anonymous namespace)::AppArmoredProcess::~AppArmoredProcess (this=0x56459eb91240, __in_chrg=<optimized out>) at /root/parts/multipass/src/src/platform/backends/shared/linux/process_factory.cpp:49
        e = <optimized out>
#14 0x000056459bcfd109 in (anonymous namespace)::AppArmoredProcess::~AppArmoredProcess (this=0x56459eb91240, __in_chrg=<optimized out>) at /root/parts/multipass/src/src/platform/backends/shared/linux/process_factory.cpp:59
        e = <optimized out>
#15 0x000056459bcea7e7 in std::default_delete<multipass::Process>::operator() (this=<optimized out>, __ptr=<optimized out>) at /usr/include/c++/7/bits/unique_ptr.h:370
No locals.
#16 std::unique_ptr<multipass::Process, std::default_delete<multipass::Process> >::reset (__p=<optimized out>, this=0x56459db0edc8) at /usr/include/c++/7/bits/unique_ptr.h:371
No locals.
#17 multipass::QemuVirtualMachine::suspend (this=0x56459db0eb00) at /root/parts/multipass/src/src/platform/backends/qemu/qemu_virtual_machine.cpp:325
No locals.
#18 0x000056459bc806cb in multipass::Daemon::<lambda(auto:2&)>::operator()<multipass::VirtualMachine> (vm=..., __closure=<optimized out>) at /root/parts/multipass/src/src/daemon/daemon.cpp:1522
        this = <optimized out>
        this = <optimized out>
#19 std::_Function_handler<grpc::Status(multipass::VirtualMachine&), multipass::Daemon::suspend(const multipass::SuspendRequest*, grpc::ServerWriter<multipass::SuspendReply>*, std::promise<grpc::Status>*)::<lambda(auto:2&)> >::_M_invoke(const std::_Any_data &, multipass::VirtualMachine &) (__functor=..., __args#0=...) at /usr/include/c++/7/bits/std_function.h:302
No locals.
#20 0x000056459bc841c2 in std::function<grpc::Status (multipass::VirtualMachine&)>::operator()(multipass::VirtualMachine&) const (__args#0=..., this=0x7fff9a1a6620) at /usr/include/c++/7/bits/std_function.h:706
No locals.
#21 multipass::Daemon::cmd_vms(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::function<grpc::Status (multipass::VirtualMachine&)>) (this=this@entry=0x7fff9a1a6f50, tgts=..., cmd=...) at /root/parts/multipass/src/src/daemon/daemon.cpp:2049
        st = {static OK = @0x56459c4f4aa0, static CANCELLED = @0x56459c4f4a40, code_ = -1140775056, error_message_ = {static npos = 18446744073709551615, 
            _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, 
              _M_p = 0x56459bc8024c <std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct<char const*>(char const*, char const*, std::forward_iterator_tag)+172> "H\213U"}, _M_string_length = 7, {
              _M_local_buf = "\000)\035\063\016\314\342\253\000\000\000\000\000\000\000", _M_allocated_capacity = 12385686286581442816}}, binary_error_details_ = {static npos = 18446744073709551615, 
            _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x7fff9a1a65d0 ""}, _M_string_length = 0, {_M_local_buf = "\230\346ɛEV\000\000\300\253\000\260u\177\000", 
              _M_allocated_capacity = 94856966432408}}}
        tgt = <optimized out>
        __for_range = @0x7fff9a1a65d0: {<std::_Vector_base<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >> = {
            _M_impl = {<std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >> = {<__gnu_cxx::new_allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >> = {<No data fields>}, <No data fields>}, _M_start = 0x56459eb99a00, _M_finish = 0x56459eb99a20, _M_end_of_storage = 0x56459eb99a20}}, <No data fields>}
        __for_begin = <optimized out>
        __for_end = <optimized out>
```

Full gdb log: [gdb.txt](https://github.com/canonical/multipass/files/4747821/gdb.txt)

**Comment by xmkg** [comment]
We haven't seen this happening for quite a while so I assume that it's fixed. If not, we can open a new issue later on.
