### ISSUE TITLE
Broken mount causes multipass(d?) to hang

### ISSUE THREAD

**Issue by Saviq** [canonical/multipass#159]
When you hit #158, multipassd is hanging, seemingly in the frame below:
```
#0  0x00007f4b1540274d in poll () from /snap/core/current/lib/x86_64-linux-gnu/libc.so.6
#1  0x0000000000728a25 in poll (__timeout=<optimized out>, __nfds=<optimized out>, __fds=<optimized out>)
    at /usr/include/x86_64-linux-gnu/bits/poll2.h:46
#2  ssh_poll (fds=<optimized out>, nfds=<optimized out>, timeout=<optimized out>)
    at /root/build_multipass/parts/multipass/src/3rd-party/libssh/libssh/src/poll.c:98
#3  0x0000000000728e17 in ssh_poll_ctx_dopoll (ctx=ctx@entry=0x2ad4960, timeout=timeout@entry=-1)
    at /root/build_multipass/parts/multipass/src/3rd-party/libssh/libssh/src/poll.c:612
#4  0x0000000000729e19 in ssh_handle_packets (session=session@entry=0x2aeedf0, timeout=timeout@entry=-1)
    at /root/build_multipass/parts/multipass/src/3rd-party/libssh/libssh/src/session.c:641
#5  0x0000000000729ef3 in ssh_handle_packets_termination (session=0x2aeedf0, timeout=<optimized out>,
    timeout@entry=-3, fct=fct@entry=0x715d30 <ssh_channel_exit_status_termination>, user=user@entry=0x2af1350)
    at /root/build_multipass/parts/multipass/src/3rd-party/libssh/libssh/src/session.c:703
#6  0x000000000071886e in ssh_channel_get_exit_status (channel=0x2af1350)
    at /root/build_multipass/parts/multipass/src/3rd-party/libssh/libssh/src/channels.c:2974
#7  0x0000000000710c89 in multipass::SSHProcess::exit_code (this=this@entry=0x7ffccea240e0)
    at /root/build_multipass/parts/multipass/src/src/ssh/ssh_process.cpp:48
#8  0x000000000070ab18 in (anonymous namespace)::run_cmd<(anonymous namespace)::check_sshfs_is_running(multipass::SSHSession&, multipass::SSHProcess&, const string&, const string&)::<lambda(multipass::SSHProcess&)>&> (
    error_handler=<synthetic pointer>..., cmd=..., session=...)
    at /root/build_multipass/parts/multipass/src/src/sshfs_mount/sshfs_mount.cpp:35
#9  (anonymous namespace)::check_sshfs_is_running (target=..., source=..., sshfs_process=..., session=...)
    at /root/build_multipass/parts/multipass/src/src/sshfs_mount/sshfs_mount.cpp:56
#10 (anonymous namespace)::create_sshfs_process (target=..., source=..., session=..., this=<optimized out>,
    this=<optimized out>, this=<optimized out>)
    at /root/build_multipass/parts/multipass/src/src/sshfs_mount/sshfs_mount.cpp:89
#11 (anonymous namespace)::make_sftp_server (cout=..., uid_map=..., gid_map=..., target=..., source=..., session=...,
    this=<optimized out>, this=<optimized out>, this=<optimized out>)
    at /root/build_multipass/parts/multipass/src/src/sshfs_mount/sshfs_mount.cpp:99
#12 multipass::SshfsMount::SshfsMount (this=0x2f2ea20, session=..., source=..., target=..., gid_map=..., uid_map=...,
    cout=...) at /root/build_multipass/parts/multipass/src/src/sshfs_mount/sshfs_mount.cpp:114
[...]
```

**Comment by townsend2010** [comment]
Yeah, I've seen this before and have looked into it and I'm really not sure what we can do about it.  The real issue is that we are mounting over the logged in user's ssh keys and configuration, so when libssh tries to get exit status (which is a blocking call) of the command to see if sshfs is running, it hangs due to never receiving said exit status from the session channel in the instance since it is b0rked.

The only way to keep this from happening is just to never allow any mounting over the instances user's home.

**Comment by Saviq** [comment]
Well, isn't it possible to isolate the blocking SSH calls from the daemon's main thread?

**Comment by townsend2010** [comment]
Sure, it's possible, but it won't be trivial due to what we are trying to accomplish here.  The daemon wants to mount something, but we also want to catch and report back any errors like sshfs failing to start, etc.  So in order to do this, the whole mount logic would need to run in a separate thread/context and then somehow report back errors to the daemon asynchronously and then the daemon report this back to the client.

What would be really nice is that libssh doesn't make this a blocking call but instead have some sort of timeout when trying to get exit status from a command that was ran in the instance...but that's not trivial either.
