### ISSUE TITLE
spark worker node couldn't connect to master

### ISSUE THREAD

**Issue by seongilp** [canonical/multipass#1618]
**Describe the bug**
Describe what your problem is.
Hi, I am trying to build spark cluster with multipass on my mac
but communication master and worker isn't work

 ~  multipass list                                                                                                                                           ✔  00:04 20/06/28
Name                    State             IPv4             Image
spark-master            Running           192.168.64.4     Ubuntu 18.04 LTS
spark-worker01          Running           192.168.64.5     Ubuntu 18.04 LTS
spark-worker02          Running           192.168.64.6     Ubuntu 18.04 LTS

/
**To Reproduce**
How, and what happened?
1. `multipass ...`
1.

**Expected behavior**
What did you expect to happen?

**Logs**
Please provide logs from the daemon, see [accessing logs](https://multipass.run/docs/accessing-logs) on where to find them on your platform.

master node listen port 7077
```
ubuntu@spark-master:~/spark-3.0.0-bin-hadoop3.2/sbin$ jps
2125 Worker
1981 Master
2222 Jps
ubuntu@spark-master:~/spark-3.0.0-bin-hadoop3.2/sbin$ lsof -i -P | grep 1981
java    1981 ubuntu  275u  IPv6  24200      0t0  TCP spark-master:7077 (LISTEN)
java    1981 ubuntu  277u  IPv6  24309      0t0  TCP spark-master:8080 (LISTEN)
java    1981 ubuntu  282u  IPv6  24888      0t0  TCP spark-master:7077->localhost:53964 (ESTABLISHED)
ubuntu@spark-master:~/spark-3.0.0-bin-hadoop3.2/sbin$
```

log of worker node as below
```
20/06/28 10:32:33 INFO Worker: Retrying connection to master (attempt # 9)
20/06/28 10:32:33 INFO Worker: Connecting to master spark-master:7077...
20/06/28 10:32:33 WARN Worker: Failed to connect to master spark-master:7077
org.apache.spark.SparkException: Exception thrown in awaitResult:
	at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:302)
	at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
	at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:101)
	at org.apache.spark.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:109)
	at org.apache.spark.deploy.worker.Worker$$anon$1.run(Worker.scala:277)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.io.IOException: Failed to connect to spark-master/192.168.64.4:7077
	at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:253)
	at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:195)
	at org.apache.spark.rpc.netty.NettyRpcEnv.createClient(NettyRpcEnv.scala:204)
	at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:202)
	at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:198)
	... 4 more
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: spark-master/192.168.64.4:7077
Caused by: java.net.ConnectException: Connection refused
	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:779)
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:702)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Additional info**
 - OS: [e.g. macOS 10.15]
- `multipass version`
- `multipass info --all`

```
multipass version                                                                                                                                        ✔  10:42 20/06/28
multipass  1.2.1+mac
multipassd 1.2.1+mac

###########################################################################################
New Multipass 1.3.0 release
Ubuntu Core appliances and much more!

Go here for more information: https://github.com/CanonicalLtd/multipass/releases/tag/v1.3.0
###########################################################################################

```

```
multipass info --all                                                                                                                                     ✔  10:40 20/06/28
Name:           primary
State:          Stopped
IPv4:           --
Release:        --
Image hash:     2f6bc5e7d9ac (Ubuntu 18.04 LTS)
Load:           --
Disk usage:     --
Memory usage:   --
Mounts:         /Users/zihado => Home
                    UID map: 501:default
                    GID map: 20:default

Name:           microk8s-vm
State:          Stopped
IPv4:           --
Release:        --
Image hash:     298fa2e49d00 (Ubuntu 18.04 LTS)
Load:           --
Disk usage:     --
Memory usage:   --

Name:           spark-master
State:          Running
IPv4:           192.168.64.4
Release:        Ubuntu 18.04.4 LTS
Image hash:     4ce2fbfc8bcd (Ubuntu 18.04 LTS)
Load:           0.20 0.20 0.17
Disk usage:     2.2G out of 4.7G
Memory usage:   378.5M out of 985.7M

Name:           spark-worker01
State:          Running
IPv4:           192.168.64.5
Release:        Ubuntu 18.04.4 LTS
Image hash:     4ce2fbfc8bcd (Ubuntu 18.04 LTS)
Load:           0.08 0.09 0.05
Disk usage:     1.9G out of 4.7G
Memory usage:   194.7M out of 985.7M

Name:           spark-worker02
State:          Running
IPv4:           192.168.64.6
Release:        Ubuntu 18.04.4 LTS
Image hash:     4ce2fbfc8bcd (Ubuntu 18.04 LTS)
Load:           0.07 0.11 0.06
Disk usage:     1.9G out of 4.7G
Memory usage:   195.5M out of 985.7M

```

**Additional context**

**Comment by Saviq** [comment]
Hi @seongilp, are you using host names to connect between the nodes? If so, that's probably the problem. The names don't resolve, you'll need to use IPs instead.
