### ISSUE TITLE
Daemon stuck deleting a LXD instance

### ISSUE THREAD

**Issue by Saviq** [canonical/multipass#1719]
Not really a way to reproduce, but what I observed is that `multipass delete --purge --all` got stuck after an instance failed to start:

```bash
$ multipass launch      
launch failed: The following errors occurred:                                   
failed to determine IP address
$ multipass delete -p --all
# stuckiness
```

`gdb` shows the daemon waiting for a lock:
```
#0  0x00007f5bbb9149f3 in pthread_cond_wait@@GLIBC_2.3.2 () from target:/lib/x86_64-linux-gnu/libpthread.so.0
No symbol table info available.
#1  0x00007f5bb9c3a8bc in std::condition_variable::wait(std::unique_lock<std::mutex>&) () from target:/usr/lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#2  0x000055fc1a735e8b in std::condition_variable::wait<multipass::LXDVirtualMachine::stop()::<lambda()> > (__p=..., __lock=..., this=0x55fc1b8ce650) at /usr/include/c++/7/condition_variable:99
No locals.
#3  multipass::LXDVirtualMachine::stop (this=0x55fc1b8ce620) at /build/multipass/parts/multipass/src/src/platform/backends/lxd/lxd_virtual_machine.cpp:255
        lock = {_M_device = 0x55fc1b8ce680, _M_owns = true}
        present_state = multipass::VirtualMachine::State::starting
        state_task = {d = 0x55fc1b32b980, o = 0x55fc1b8b4548}
#4  0x000055fc1a6b6a8d in multipass::Daemon::delet (this=0x7ffd5f7a97b0, request=0x7f5b88026c10, server=<optimized out>, status_promise=0x7f5b9932e720) at /build/multipass/parts/multipass/src/src/daemon/daemon.cpp:1661
        instance = @0x55fc1b3251c8: {<std::__shared_ptr<multipass::VirtualMachine, (__gnu_cxx::_Lock_policy)2>> = {<std::__shared_ptr_access<multipass::VirtualMachine, (__gnu_cxx::_Lock_policy)2, false, false>> = {<No data fields>}, _M_ptr = 0x55fc1b8ce620, 
            _M_refcount = {_M_pi = 0x55fc1b32e430}}, <No data fields>}
        name = <optimized out>
        __for_range = @0x7ffd5f7a8f20: {<std::_Vector_base<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >> = {
            _M_impl = {<std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >> = {<__gnu_cxx::new_allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >> = {<No data fields>}, <No data fields>}, _M_start = 0x55fc1b8b8c80, _M_finish = 0x55fc1b8b8ca0, _M_end_of_storage = 0x55fc1b8b8ca0}}, <No data fields>}
        __for_begin = <optimized out>
        __for_end = <optimized out>
        purge = true
        logger = {<multipass::logging::Logger> = {_vptr.Logger = 0x55fc1af02a98 <vtable for multipass::logging::ClientLogger<multipass::DeleteReply>+16>}, logging_level = multipass::logging::Level::error, server = 0x7f5b9932e830, mpx_logger = @0x55fc1b2b2480}
        operational_instances_to_delete = <optimized out>
        trashed_instances_to_delete = <optimized out>
        status = <optimized out>
```

More `gdb` output: [gdb.txt](https://github.com/canonical/multipass/files/5168438/gdb.txt)

Log is quite scarce…
```
wrz 03 14:15:06 michal-laptop multipassd[2591586]: QFileInfo::absolutePath: Constructed with empty filename
wrz 03 14:15:06 michal-laptop multipassd[2591586]: Creating container with stream: https://cloud-images.ubuntu.com/releases/, id: 05363a30d9f2aa636961a646ea57470b0ed536a1466aa7914699f210a17662ac
wrz 03 14:18:29 michal-laptop multipassd[2591586]: No mounts to stop for instance "engaging-turkey"
```

**Comment by townsend2010** [comment]
I think I see the problem in the code.  Will work on a fix soon.
