### ISSUE TITLE
[lxd] Crash and "Failed getting NIC state" on `multipass delete -p --all`

### ISSUE THREAD

**Issue by Saviq** [canonical/multipass#2071]
```plain
$ multipass version
multipass  1.7.0-dev.426+g5057c2ea
multipassd 1.7.0-dev.426+g5057c2ea

$ lxc version
Client version: 4.13
Server version: 4.13

$ multipass list
Name                    State             IPv4             Image
darling-whistler        Running           10.152.94.234    Ubuntu 20.04 LTS

$ multipass delete -p --all
 - Failed getting NIC state for "eth0": Failed getting host interface state for "tapb0236623": route ip+net: no such network interfacehines/darling-whistler/state?project=multipass: Internal Server Error
```

**Comment by Saviq** [comment]
I think we're asking LXD for the state of an instance that's in process of being deleted:

```plain
kwi 23 19:56:37 michal-laptop multipassd[808777]: Requesting LXD: GET unix://multipass/var/snap/lxd/common/lxd/unix.socket@1.0/virtual-machines/promoting-chinook/state?project=multipass
kwi 23 19:56:39 michal-laptop multipassd[808777]: Got reply: {
                                                      "error": "Failed getting NIC state for \"eth0\": Failed getting host interface state for \"\": route ip+net: invalid network interface name",
                                                      "error_code": 500,
                                                      "type": "error"
                                                  }
kwi 23 19:56:39 michal-laptop multipassd[808777]: Network error for unix://multipass/var/snap/lxd/common/lxd/unix.socket@1.0/virtual-machines/promoting-chinook/state?project=multipass: Internal Server Error^M - Failed getting NIC state for "eth0": Failed gettin>
```

**Comment by Saviq** [comment]
I got it to crash by `while multipass launch 21.04 && multipass delete -p --all; do true; done`:

```gdb
#0  multipass::Daemon::list (this=0x7fff93cd2710, request=0x7f5c00181070, server=0x7f5c0effc7c0, status_promise=0x7f5c0effc650) at /usr/include/c++/9/bits/shared_ptr_base.h:1020
#1  0x00007f5c2b637d5a in QObject::event(QEvent*) () from target:/snap/multipass/4296/usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#2  0x00007f5c2b60b917 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from target:/snap/multipass/4296/usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#3  0x00007f5c2b60e5b8 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () from target:/snap/multipass/4296/usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#4  0x00007f5c2b663f67 in ?? () from target:/snap/multipass/4296/usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#5  0x00007f5c2a47e17d in g_main_context_dispatch () from target:/lib/x86_64-linux-gnu/libglib-2.0.so.0
#6  0x00007f5c2a47e400 in ?? () from target:/lib/x86_64-linux-gnu/libglib-2.0.so.0
#7  0x00007f5c2a47e4a3 in g_main_context_iteration () from target:/lib/x86_64-linux-gnu/libglib-2.0.so.0
#8  0x00007f5c2b663565 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from target:/snap/multipass/4296/usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#9  0x00007f5c2b60a4db in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from target:/snap/multipass/4296/usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#10 0x00007f5c2b612246 in QCoreApplication::exec() () from target:/snap/multipass/4296/usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#11 0x0000564f16b6438f in (anonymous namespace)::main_impl (argc=<optimized out>, argv=<optimized out>) at /build/multipass/parts/multipass/src/src/daemon/daemon_main.cpp:127
#12 0x0000564f16b5ba58 in std::__invoke_impl<int, int (&)(int, char**), int&, char**&> (__f=@0x564f16b63bc0: {int (int, char **)} 0x564f16b63bc0 <(anonymous namespace)::main_impl(int, char**)>) at /usr/include/c++/9/bits/invoke.h:89
#13 std::__invoke<int (&)(int, char**), int&, char**&> (__fn=@0x564f16b63bc0: {int (int, char **)} 0x564f16b63bc0 <(anonymous namespace)::main_impl(int, char**)>) at /usr/include/c++/9/bits/invoke.h:95
#14 std::invoke<int (&)(int, char**), int&, char**&> (__fn=@0x564f16b63bc0: {int (int, char **)} 0x564f16b63bc0 <(anonymous namespace)::main_impl(int, char**)>) at /usr/include/c++/9/functional:81
#15 multipass::top_catch_all<int, int (&)(int, char**), int&, char**&> (f=@0x564f16b63bc0: {int (int, char **)} 0x564f16b63bc0 <(anonymous namespace)::main_impl(int, char**)>, fallback_return=<optimized out>, log_category=...) at /build/multipass/parts/multipass/src/include/multipass/top_catch_all.h:84
#16 main (argc=<optimized out>, argv=<optimized out>) at /build/multipass/parts/multipass/src/src/daemon/daemon_main.cpp:136
```

Full trace: [gdb.txt](https://github.com/canonical/multipass/files/6368149/gdb.txt)
