### ISSUE TITLE
ServerConfigurationOptions.are_read_from_xdg_config_home segfaults on focal

### ISSUE THREAD

**Issue by Saviq** [canonical/multipass#2517]
Having built mir on Focal, the test cleanup fails:

```plain
$ build/bin/mir_acceptance_tests --gtest_filter=ServerConfigurationOptions.are_read_from_xdg_config_home
MIR_SERVER_PLATFORM_PATH=build/bin/../lib/server-modules/
LD_LIBRARY_PATH=build/bin/../lib
exec=build/bin/mir_acceptance_tests.bin
Running main() from main.cpp
Note: Google Test filter = ServerConfigurationOptions.are_read_from_xdg_config_home
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from ServerConfigurationOptions
[ RUN      ] ServerConfigurationOptions.are_read_from_xdg_config_home
[       OK ] ServerConfigurationOptions.are_read_from_xdg_config_home (24 ms)
[----------] 1 test from ServerConfigurationOptions (24 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (24 ms total)
[  PASSED  ] 1 test.
Segmentation fault (core dumped)
```

```gdb
#0  0x0000fffff2e90f4c in std::__cxx11::_List_base<std::function<std::optional<int> (char const*, int, std::optional<unsigned int>)>, std::allocator<std::function<std::optional<int> (char const*, int, std::optional<unsigned int>)> > >::_M_clear() (this=0xfffff2f2e5a0 <(anonymous namespace)::OpenHandlers::instance()::open_handlers+48>) at /usr/include/c++/9/bits/list.tcc:74
        __tmp = 0x0
        __val = 0xfffff2f276d8 <(anonymous namespace)::display_preset>
        __cur = 0x0
#1  0x0000fffff2e903ec in std::__cxx11::_List_base<std::function<std::optional<int> (char const*, int, std::optional<unsigned int>)>, std::allocator<std::function<std::optional<int> (char const*, int, std::optional<unsigned int>)> > >::~_List_base() (this=0xfffff2f2e5a0 <(anonymous namespace)::OpenHandlers::instance()::open_handlers+48>, __in_chrg=<optimized out>)
    at /usr/include/c++/9/bits/stl_list.h:495
#2  0x0000fffff2e8f930 in std::__cxx11::list<std::function<std::optional<int> (char const*, int, std::optional<unsigned int>)>, std::allocator<std::function<std::optional<int> (char const*, int, std::optional<unsigned int>)> > >::~list() (this=0xfffff2f2e5a0 <(anonymous namespace)::OpenHandlers::instance()::open_handlers+48>, __in_chrg=<optimized out>) at /usr/include/c++/9/bits/stl_list.h:823
#3  0x0000fffff2e8d0d4 in (anonymous namespace)::OpenHandlers::~OpenHandlers() (this=0xfffff2f2e570 <(anonymous namespace)::OpenHandlers::instance()::open_handlers>, __in_chrg=<optimized out>)
    at ../tests/mir_test_framework/open_wrapper.cpp:39
#4  0x0000fffff5fb1a14 in __cxa_finalize (d=0xfffff2ef9410) at cxa_finalize.c:83
```

[gdb.txt](https://github.com/canonical/multipass/files/8465926/gdb.txt)

**Comment by Saviq** [comment]
Wrong repository…
