### ISSUE TITLE
multipass blocks trying to restart a suspended instance

### ISSUE THREAD

**Issue by ricab** [canonical/multipass#764]
Instead of refusing to restart a suspended instance right away (saing it was not running), multipass did try to go through with `multipass restart`. However, it never returned. 

The daemon then failed to quit on SIGINT or SIGTERM, hanging after printing "Goodbye". It did quit on SIGHUP, for which there is no custom handler, leaving children running behind.

I managed to reproduce this consistently:

```
ricab@ricab-xps13:~/mydev/multipass/build $ multipass launch -n foo
Launched: foo
ricab@ricab-xps13:~/mydev/multipass/build $ multipass list
Name                    State             IPv4             Release
foo                     RUNNING           10.13.33.126     Ubuntu 18.04 LTS
ricab@ricab-xps13:~/mydev/multipass/build $ multipass suspend foo
ricab@ricab-xps13:~/mydev/multipass/build $ multipass list
Name                    State             IPv4             Release
foo                     SUSPENDED         --               Ubuntu 18.04 LTS
ricab@ricab-xps13:~/mydev/multipass/build $ multipass restart foo
Restarting foo -^C
```
The stacktrace below (of the daemon, after the first SIGINT)  shows Thread 5 still in `DaemonRpc::restart`:

```
(gdb) i thr
  Id   Target Id                                          Frame
* 1    Thread 0x7ff47e6c8bc0 (LWP 8977) "multipassd"      futex_wait_cancelable (
    private=<optimized out>, expected=0, futex_word=0x564709fa59e0)
    at ../sysdeps/unix/sysv/linux/futex-internal.h:88
  2    Thread 0x7ff47c8e8700 (LWP 9041) "default-executo" futex_wait_cancelable (
    private=<optimized out>, expected=0, futex_word=0x564709fc4664)
    at ../sysdeps/unix/sysv/linux/futex-internal.h:88
  3    Thread 0x7ff47d0e9700 (LWP 9042) "resolver-execut" futex_wait_cancelable (
    private=<optimized out>, expected=0, futex_word=0x564709fc3a70)
    at ../sysdeps/unix/sysv/linux/futex-internal.h:88
  4    Thread 0x7ff477fff700 (LWP 9043) "grpc_global_tim" futex_wait_cancelable (
    private=<optimized out>, expected=0, futex_word=0x5647095a7148 <g_cv_wait+40>)
    at ../sysdeps/unix/sysv/linux/futex-internal.h:88
  5    Thread 0x7ff4777fe700 (LWP 9044) "grpcpp_sync_ser" syscall ()
    at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
  6    Thread 0x7ff4767fc700 (LWP 9046) "Qt bearer threa" 0x00007ff485c906d9 in __GI___poll (
    fds=0x7ff45c003ce0, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
  7    Thread 0x7ff475ffb700 (LWP 9047) "QDBusConnection" 0x00007ff485c906d9 in __GI___poll (
    fds=0x7ff460004db0, nfds=2, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
  8    Thread 0x7ff452ffd700 (LWP 9123) "grpcpp_sync_ser" syscall ()
    at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
  9    Thread 0x7ff453fff700 (LWP 9134) "grpc_global_tim" futex_reltimed_wait_cancelable (
    private=<optimized out>, reltime=0x7ff453ffe880, expected=0,
    futex_word=0x5647095a7148 <g_cv_wait+40>) at ../sysdeps/unix/sysv/linux/futex-internal.h:142
(gdb) thr apply all where

Thread 9 (Thread 0x7ff453fff700 (LWP 9134)):
#0  futex_reltimed_wait_cancelable (private=<optimized out>, reltime=0x7ff453ffe880, expected=0,
    futex_word=0x5647095a7148 <g_cv_wait+40>) at ../sysdeps/unix/sysv/linux/futex-internal.h:142
#1  __pthread_cond_wait_common (abstime=0x7ff453ffe930, mutex=0x5647095a7160 <_ZL4g_mu>,
    cond=0x5647095a7120 <g_cv_wait>) at pthread_cond_wait.c:533
#2  __pthread_cond_timedwait (cond=0x5647095a7120 <g_cv_wait>, mutex=0x5647095a7160 <_ZL4g_mu>,
    abstime=0x7ff453ffe930) at pthread_cond_wait.c:667
#3  0x00005647092d0bea in gpr_cv_wait ()
#4  0x000056470911cdab in timer_thread(void*) ()
#5  0x00005647092d2044 in grpc_core::(anonymous namespace)::ThreadInternalsPosix::ThreadInternalsPosix(char const*, void (*)(void*), void*, bool*)::{lambda(void*)#1}::_FUN(void*) ()
#6  0x00007ff486608164 in start_thread (arg=<optimized out>) at pthread_create.c:486
#7  0x00007ff485c9cdef in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 8 (Thread 0x7ff452ffd700 (LWP 9123)):
#0  syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
#1  0x00007ff485fcf511 in std::__atomic_futex_unsigned_base::_M_futex_wait_until(unsigned int*, unsigned int, bool, std::chrono::duration<long, std::ratio<1l, 1l> >, std::chrono::duration<long, std::ratio<1l, 1000000000l> >) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#2  0x000056470902ee52 in std::future<grpc::Status>::get() ()
#3  0x000056470902d961 in multipass::DaemonRpc::restart(grpc::ServerContext*, multipass::RestartRequest const*, grpc::ServerWriter<multipass::RestartReply>*) ()
#4  0x00005647090913c2 in std::_Function_handler<grpc::Status (multipass::Rpc::Service*, grpc::ServerContext*, multipass::RestartRequest const*, grpc::ServerWriter<multipass::RestartReply>*), std::_Mem_fn<grpc::Status (multipass::Rpc::Service::*)(grpc::ServerContext*, multipass::RestartRequest const*, grpc::ServerWriter<multipass::RestartReply>*)> >::_M_invoke(std::_Any_data const&, multipass::Rpc::Service*&&, grpc::ServerContext*&&, multipass::RestartRequest const*&&, grpc::ServerWriter<multipass::RestartReply>*&&) ()
#5  0x00005647090a3c56 in grpc::Status grpc::internal::CatchingFunctionHandler<grpc::internal::ServerStreamingHandler<multipass::Rpc::Service, multipass::RestartRequest, multipass::RestartReply>::RunHandler(grpc::internal::MethodHandler::HandlerParameter const&)::{lambda()#1}>(grpc::internal::ServerStreamingHandler<multipass::Rpc::Service, multipass::RestartRequest, multipass::RestartReply>::RunHandler(grpc::internal::MethodHandler::HandlerParameter const&)::{lambda()#1}&&) ()
#6  0x00005647090b5a71 in grpc::internal::ServerStreamingHandler<multipass::Rpc::Service, multipass::RestartRequest, multipass::RestartReply>::RunHandler(grpc::internal::MethodHandler::HandlerParameter const&) ()
#7  0x0000564709102c3d in grpc::Server::SyncRequestThreadManager::DoWork(void*, bool, bool) ()
#8  0x0000564709105338 in grpc::ThreadManager::MainWorkLoop() ()
#9  0x00005647091053fc in grpc::ThreadManager::WorkerThread::Run() ()
#10 0x00005647092d2044 in grpc_core::(anonymous namespace)::ThreadInternalsPosix::ThreadInternalsPosix(char const*, void (*)(void*), void*, bool*)::{lambda(void*)#1}::_FUN(void*) ()
#11 0x00007ff486608164 in start_thread (arg=<optimized out>) at pthread_create.c:486
#12 0x00007ff485c9cdef in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 7 (Thread 0x7ff475ffb700 (LWP 9047)):
#0  0x00007ff485c906d9 in __GI___poll (fds=0x7ff460004db0, nfds=2, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007ff483338e46 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ff483338f6c in g_main_context_iteration () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007ff48635b143 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#4  0x00007ff48630816b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#5  0x00007ff4861570b6 in QThread::exec() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#6  0x00007ff47c01c545 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5DBus.so.5
#7  0x00007ff486160c87 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#8  0x00007ff486608164 in start_thread (arg=<optimized out>) at pthread_create.c:486
#9  0x00007ff485c9cdef in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 6 (Thread 0x7ff4767fc700 (LWP 9046)):
#0  0x00007ff485c906d9 in __GI___poll (fds=0x7ff45c003ce0, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007ff483338e46 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ff483338f6c in g_main_context_iteration () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007ff48635b143 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#4  0x00007ff48630816b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#5  0x00007ff4861570b6 in QThread::exec() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#6  0x00007ff486160c87 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#7  0x00007ff486608164 in start_thread (arg=<optimized out>) at pthread_create.c:486
#8  0x00007ff485c9cdef in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 5 (Thread 0x7ff4777fe700 (LWP 9044)):
#0  syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
#1  0x00007ff485fcf511 in std::__atomic_futex_unsigned_base::_M_futex_wait_until(unsigned int*, unsigned int, bool, std::chrono::duration<long, std::ratio<1l, 1l> >, std::chrono::duration<long, std::ratio<1l, 1000000000l> >) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#2  0x000056470902ee52 in std::future<grpc::Status>::get() ()
#3  0x000056470902d961 in multipass::DaemonRpc::restart(grpc::ServerContext*, multipass::RestartRequest const*, grpc::ServerWriter<multipass::RestartReply>*) ()
#4  0x00005647090913c2 in std::_Function_handler<grpc::Status (multipass::Rpc::Service*, grpc::ServerContext*, multipass::RestartRequest const*, grpc::ServerWriter<multipass::RestartReply>*), std::_Mem_fn<grpc::Status (multipass::Rpc::Service::*)(grpc::ServerContext*, multipass::RestartRequest const*, grpc::ServerWriter<multipass::RestartReply>*)> >::_M_invoke(std::_Any_data const&, multipass::Rpc::Service*&&, grpc::ServerContext*&&, multipass::RestartRequest const*&&, grpc::ServerWriter<multipass::RestartReply>*&&) ()
#5  0x00005647090a3c56 in grpc::Status grpc::internal::CatchingFunctionHandler<grpc::internal::ServerStreamingHandler<multipass::Rpc::Service, multipass::RestartRequest, multipass::RestartReply>::RunHandler(grpc::internal::MethodHandler::HandlerParameter const&)::{lambda()#1}>(grpc::internal::ServerStreamingHandler<multipass::Rpc::Service, multipass::RestartRequest, multipass::RestartReply>::RunHandler(grpc::internal::MethodHandler::HandlerParameter const&)::{lambda()#1}&&) ()
#6  0x00005647090b5a71 in grpc::internal::ServerStreamingHandler<multipass::Rpc::Service, multipass::RestartRequest, multipass::RestartReply>::RunHandler(grpc::internal::MethodHandler::HandlerParameter const&) ()
#7  0x0000564709102c3d in grpc::Server::SyncRequestThreadManager::DoWork(void*, bool, bool) ()
#8  0x0000564709105338 in grpc::ThreadManager::MainWorkLoop() ()
#9  0x00005647091053fc in grpc::ThreadManager::WorkerThread::Run() ()
#10 0x00005647092d2044 in grpc_core::(anonymous namespace)::ThreadInternalsPosix::ThreadInternalsPosix(char const*, void (*)(void*), void*, bool*)::{lambda(void*)#1}::_FUN(void*) ()
#11 0x00007ff486608164 in start_thread (arg=<optimized out>) at pthread_create.c:486
#12 0x00007ff485c9cdef in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 4 (Thread 0x7ff477fff700 (LWP 9043)):
#0  futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x5647095a7148 <g_cv_wait+40>) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
#1  __pthread_cond_wait_common (abstime=0x0, mutex=0x5647095a7160 <_ZL4g_mu>, cond=0x5647095a7120 <g_cv_wait>) at pthread_cond_wait.c:502
#2  __pthread_cond_wait (cond=0x5647095a7120 <g_cv_wait>, mutex=0x5647095a7160 <_ZL4g_mu>) at pthread_cond_wait.c:655
#3  0x00005647092d0b72 in gpr_cv_wait ()
#4  0x000056470911cdab in timer_thread(void*) ()
#5  0x00005647092d2044 in grpc_core::(anonymous namespace)::ThreadInternalsPosix::ThreadInternalsPosix(char const*, void (*)(void*), void*, bool*)::{lambda(void*)#1}::_FUN(void*) ()
#6  0x00007ff486608164 in start_thread (arg=<optimized out>) at pthread_create.c:486
#7  0x00007ff485c9cdef in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 3 (Thread 0x7ff47d0e9700 (LWP 9042)):
#0  futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x564709fc3a70) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
#1  __pthread_cond_wait_common (abstime=0x0, mutex=0x564709fc3a10, cond=0x564709fc3a48) at pthread_cond_wait.c:502
#2  __pthread_cond_wait (cond=0x564709fc3a48, mutex=0x564709fc3a10) at pthread_cond_wait.c:655
#3  0x00005647092d0b72 in gpr_cv_wait ()
#4  0x00005647091115c0 in GrpcExecutor::ThreadMain(void*) ()
#5  0x00005647092d2044 in grpc_core::(anonymous namespace)::ThreadInternalsPosix::ThreadInternalsPosix(char const*, void (*)(void*), void*, bool*)::{lambda(void*)#1}::_FUN(void*) ()
#6  0x00007ff486608164 in start_thread (arg=<optimized out>) at pthread_create.c:486
#7  0x00007ff485c9cdef in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 2 (Thread 0x7ff47c8e8700 (LWP 9041)):
#0  futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x564709fc4664) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
#1  __pthread_cond_wait_common (abstime=0x0, mutex=0x564709fc4600, cond=0x564709fc4638) at pthread_cond_wait.c:502
#2  __pthread_cond_wait (cond=0x564709fc4638, mutex=0x564709fc4600) at pthread_cond_wait.c:655
#3  0x00005647092d0b72 in gpr_cv_wait ()
#4  0x00005647091115c0 in GrpcExecutor::ThreadMain(void*) ()
#5  0x00005647092d2044 in grpc_core::(anonymous namespace)::ThreadInternalsPosix::ThreadInternalsPosix(char const*, void (*)(void*), void*, bool*)::{lambda(void*)#1}::_FUN(void*) ()
#6  0x00007ff486608164 in start_thread (arg=<optimized out>) at pthread_create.c:486
#7  0x00007ff485c9cdef in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 1 (Thread 0x7ff47e6c8bc0 (LWP 8977)):
#0  futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x564709fa59e0) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
#1  __pthread_cond_wait_common (abstime=0x0, mutex=0x564709fa5988, cond=0x564709fa59b8) at pthread_cond_wait.c:502
#2  __pthread_cond_wait (cond=0x564709fa59b8, mutex=0x564709fa5988) at pthread_cond_wait.c:655
#3  0x00007ff485fcb8ac in std::condition_variable::wait(std::unique_lock<std::mutex>&) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x0000564709104a33 in grpc::ThreadManager::Wait() ()
#5  0x00005647090fb739 in grpc::Server::ShutdownInternal(gpr_timespec) ()
#6  0x00005647090fbc15 in grpc::Server::~Server() ()
#7  0x00005647090fbc69 in grpc::Server::~Server() ()
#8  0x0000564708ffbd1c in multipass::Daemon::~Daemon() ()
#9  0x0000564708fe9801 in main ()
```

**Comment by ricab** [comment]
BTW, I did wait for more than 5min before ctrl-c'ing the client and there was no timeout.
