### ISSUE TITLE
Daemon crash on `stop --all`

### ISSUE THREAD

**Issue by Saviq** [canonical/multipass#964]
Just had this:

```
$ multipass stop --all
Stopping all instances -[2019-08-13T22:59:13.320] [error] [sftp server] sshfs in the instance appears to have exited unexpectedly.  Trying to recover.                                                                                       

stop failed: cannot connect to the multipass socket
Please ensure multipassd is running and '/var/snap/multipass/common/multipass_socket' is accessible
```

**Comment by Saviq** [comment]
To reproduce, start and stop an instance with mounts configured a number of times.

I only managed to get this trace:
```
#0  0x00007f8a21056428 in raise () from /snap/core/current/lib/x86_64-linux-gnu/libc.so.6
No symbol table info available.
#1  0x00007f8a2105802a in abort () from /snap/core/current/lib/x86_64-linux-gnu/libc.so.6
No symbol table info available.
#2  0x00007f8a2199984d in __gnu_cxx::__verbose_terminate_handler() () from /snap/core/current/usr/lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#3  0x00007f8a219976b6 in ?? () from /snap/core/current/usr/lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#4  0x00007f8a21997701 in std::terminate() () from /snap/core/current/usr/lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#5  0x00007f8a219c2d38 in ?? () from /snap/core/current/usr/lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#6  0x00007f8a2241c6ba in start_thread () from /snap/core/current/lib/x86_64-linux-gnu/libpthread.so.0
No symbol table info available.
#7  0x00007f8a2112841d in clone () from /snap/core/current/lib/x86_64-linux-gnu/libc.so.6
No symbol table info available.
```

Full thread stacktrace [here](https://pastebin.ubuntu.com/p/h5BSTXhyCS/) as I couldn't get github to attach the file…
